# Numpy

Numpy is the core library for scientific and numerical computing in Python. It provides high-performance multidimensional array objects and tools for working with arrays.

It main objective is a multidimensional array. Every dimension is also known as an axis.

### Numpy vs Python list

1) Numpy is optimized over years and is much faster than python lists
2) Numpy has much more functionality than python list and is more convenient to use
3) Numpy is optimized to use less memory than python list


## Importing a numpy array

In [1]:
import numpy as np

## Creating a numpy array

Data type of numpy array :

<img src="https://miro.medium.com/max/1240/1*lbPigku_qn_NeKAHHTGYPg.png" alt="Data types of numpy array">

In [2]:
array = np.array([1,2,3])
print(array)

[1 2 3]


In [3]:
array = np.array([1, 2, 3], dtype=np.float64) ## dtype is the datatype
print(array)

[1. 2. 3.]


## Comparing Numpy array with Python list

In [4]:
import time as t
import sys

### Memory Consumed by Python List

In [5]:
pyList = range(1000)
print(sys.getsizeof(pyList) * len(pyList))

48000


### Memory Consumed by Numpy array

In [6]:
npArray = np.arange(1000)
print(npArray.itemsize * npArray.size)

4000


### Time Consumed by Pyton List

In [7]:
size = 10000

In [8]:
pyList = range(size)
pyList2 = range(size)
start = t.time()
result = [(x+y) for x,y in zip(pyList, pyList2)]
print("Time taken by python list: ", (t.time() - start)*1000)

Time taken by python list:  9.695291519165039


### Time Consumed by Numpy Array

In [9]:
npArray = np.arange(size)
npArray2 = np.arange(size)
start = t.time()
result = npArray + npArray2
print("Time taken by numpy array: ", (t.time() - start)*1000)

Time taken by numpy array:  0.0


## Basics of Numpy

In [10]:
array = np.array([[1, 2, 2], [3, 4, 5], [6, 7, 8]])

### Dimensions of the array

It tells us the number of nested arrays. 

If a jaggered array is given as input, then the jaggered array is of type object and is not treated as an array. In this case, the number of dimensions would not include the jaggered array.

Jaggered array -> A nested array with different sizes.

Example : 

[[1, 3], [1, 3, 5], [1, 7, 9]]

In [11]:
print(array.ndim)

2


### Size of the array

Gives the total number of elements present in the array

In [12]:
print(array.size)

9


### Shape of the array

Returns a tuple (x, y) -> where,

x = number of rows

y = number of columns

In [13]:
print(array.shape)

(3, 3)


### Size of each individual element of the array

Returns the space occupied by an individual array element

In [14]:
print(array.itemsize)

4


## Range and arrange function

### Zeroes

Accepts a tuple (x, y), where x is the number of rows and y is the number of columns and returns a numpy array filled with zeroes.

In [15]:
print(np.zeros((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


### Ones

Accepts a tuple (x, y), where x is the number of rows and y is the number of columns and returns a numpy array filled with ones.

In [16]:
print(np.ones((2, 3)))

[[1. 1. 1.]
 [1. 1. 1.]]


### Arange

Accepts an interger n and returns an numpy array with elements from 0 to n-1 based on the step size

In [17]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


## String Functions

### Concatenation of Strings in numpy

np.char.add -> Accepts one dimensional array of equal size, and concats them into one single array

In [18]:
print(np.char.add(["Hello ", "Hey "], ["Numpy" ,"Man"]))

['Hello Numpy' 'Hey Man']


### Capitalize Strings

np.char.capitalize -> Accepts a string and returns the capitalized string 

(Only the first word is capitalized)

In [19]:
print(np.char.capitalize("hey man.hey"))

Hey man.hey


### Title Strings

np.char.title -> Accepts a string and returns the titled string

(All the words are capitalized)

In [20]:
print(np.char.title("hey man"))

Hey Man


### Center

np.char.center -> Accepts the string to center, the length of new string and the filling character and returns a centered string padded by the filling character

In [21]:
print(np.char.center("center me", 20, fillchar="-"))

-----center me------


### Lower

np.char.lower -> Accepts a string or an array and returns the lower cased version

In [22]:
print(np.char.lower(["Hi"]))

['hi']


### Split

np.char.split -> Accepts a string and splits it into words

In [23]:
print(np.char.split("Split this into words"))

['Split', 'this', 'into', 'words']


### Strip

np.char.strip -> Accepts a string and a character and removes the specified characters from the start and end part of the string

In [24]:
print(np.char.strip(["Strip", "This", "Into", "Many", "Things"], 's'))

['Strip' 'Thi' 'Into' 'Many' 'Thing']


### Join

np.char.join -> Accepts the joining characters and the strings to be joined and joins them

In [25]:
print(np.char.join(["-", "@"], ["Join", "This"]))

['J-o-i-n' 'T@h@i@s']


### Replace

np.char.replace -> Accepts the string, the word to be replaced and the replacing word and returns the replaced string

In [26]:
print(np.char.replace("Replace the word replace", "replace", "man"))

Replace the word man


## Array Manipulation

### Reshaping an array

array.reshape(a1, a2, ..., an) -> An array can be reshaped under the condition that a1 x a2 x a3 x .... x an = number of elements in the original array

In [27]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reshapedArray = array.reshape(2, 2, 2)
print(reshapedArray)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Flattening an array

array.flatten(order = 'C') -> Converts the array into a 1d array

order{‘C’, ‘F’, ‘A’, ‘K’}

‘C’ means to flatten in row-major (C-style) order. ‘F’ means to flatten in column-major (Fortran- style) order. ‘A’ means to flatten in column-major order if a is Fortran contiguous in memory, row-major order otherwise. ‘K’ means to flatten a in the order the elements occur in memory. The default is ‘C’.

In [28]:
array = np.array([[1,2], [3,4]])
print(array.flatten())
print(array.flatten("F"))

[1 2 3 4]
[1 3 2 4]


### Transpose

np.transpose(matrix) -> Interchanges the rows with columns

In [29]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print(np.transpose(array))

[[1 4]
 [2 5]
 [3 6]]


### Rollaxis

np.rollaxis(array, axis, start=0) -> Changes the position of the axis mentioned to the start defined in the function and roll the other axis respectively in order to accomodate.

In [30]:
array = np.ones((1, 2, 3)) # x -> 1, y -> 2, z -> 3
print(array.shape)
array = np.rollaxis(array, 2, 0) # x -> 3, y-> 1, z -> 2
print(array.shape)

(1, 2, 3)
(3, 1, 2)


### Swapaxes

np.swapaxes(array, axis1, axis2) -> Swaps the position of the axis

In [31]:
array = np.ones((1, 2, 3)) # x -> 1, y -> 2, z -> 3
print(array.shape)
array = np.swapaxes(array, 2, 0) # x -> 3, y-> 2, z -> 1
print(array.shape)

(1, 2, 3)
(3, 2, 1)


## Numpy Arithmetic Operations

### Add

np.add(array1, array2) -> Adds both the arrays and returns the result. The columns should be the same in both the arrays and the number of rows can be either equal or one.

In [32]:
array1 = np.arange(12).reshape(4, 3)
array2 = np.array([1, 2, 3])

print(np.add(array1, array2))

[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]
 [10 12 14]]


### Subtract

np.subtract(array1, array2) -> Subtracts array2 from array1. The columns should be the same in both the arrays and the number of rows can be either equal or one.

In [33]:
array1 = np.arange(12).reshape(4, 3)
array2 = np.array([1, 2, 3])

print(np.subtract(array1, array2))

[[-1 -1 -1]
 [ 2  2  2]
 [ 5  5  5]
 [ 8  8  8]]


### Multiply

np.multiply(array1, array2) -> Multiplies array1 with array2. 

In [34]:
array1 = np.arange(9).reshape(3, 3)
array2 = np.array([1, 2, 3])

print(np.multiply(array1, array2))

[[ 0  2  6]
 [ 3  8 15]
 [ 6 14 24]]


### Divide

np.divide(array1, array2) -> Divides array1 with array2. 

In [35]:
array1 = np.arange(9).reshape(3, 3)
array2 = np.array([1, 2, 3])

print(np.divide(array1, array2))

[[0.         0.5        0.66666667]
 [3.         2.         1.66666667]
 [6.         3.5        2.66666667]]


## Slicing

### General Method

array = array[x:y] -> x represents the start and y represents the end. Elements from index x till index y-1 are selected

In [36]:
array = np.arange(10)
array = array[:5]
print(array)

[0 1 2 3 4]


### Slice Method

slice(start, end, step) -> Elements from start till end-1 indeces are seleceted based on the step size mentioned.

In [37]:
array = np.arange(20)
select = slice(5, 15, 3)
print(array[select])

[ 5  8 11 14]


## Iterating over arrays

### Iterating in c-style (C language)

Array is iterated row wise. It is the default order.

In [38]:
array = np.arange(20).reshape(4, 5)
print(array)

for ele in np.nditer(array, order="C"):
    print(ele)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


### Iterating in f-style (Fortan language)

Array is iterated column wise

In [39]:
array = np.arange(20).reshape(4, 5)
print(array)

for ele in np.nditer(array, order="F"):
    print(ele)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
0
5
10
15
1
6
11
16
2
7
12
17
3
8
13
18
4
9
14
19


## Joining arrays

np.concatenate((array1, array2, ... arrayn), axis=0) -> Arrays are joined and returned. The default way of joining is row wise(axis = 0).

When axis is 0, the arrays are joined vertically

When axis is 1, the arrays are joined horizontally

In [40]:
array1 = np.arange(4).reshape(2, 2)
array2 = np.arange(4, 8).reshape(2,2)

print("Joining vertically")
print(np.concatenate((array1, array2)))
print("Joining horizontally")
print(np.concatenate((array1, array2), axis=1))

Joining vertically
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
Joining horizontally
[[0 1 4 5]
 [2 3 6 7]]


## Splitting the array

In [41]:
array = np.arange(9, 18)

print(np.split(array, 3)) # Splits into three different arrays
print(np.split(array, [4])) # Splits at the index 4
print(np.split(array, [3, 8])) # Splits at the index 3 and 8

[array([ 9, 10, 11]), array([12, 13, 14]), array([15, 16, 17])]
[array([ 9, 10, 11, 12]), array([13, 14, 15, 16, 17])]
[array([ 9, 10, 11]), array([12, 13, 14, 15, 16]), array([17])]


## Resizing an array

np.resize(array, (x, y)) -> Resizes the array into x rows and y columns.

The main difference between resize and reshape is that resize does not give any error if the product of x and y does not match the number of elements present in the array

In [42]:
array = np.arange(1, 7).reshape(3, 2)
print(array)
resized = np.resize(array, (2, 3))
print(resized)
resized2 = np.resize(array, (3,4))
print(resized2) 

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3 4]
 [5 6 1 2]
 [3 4 5 6]]
